version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    command:
      - '--web.enable-lifecycle'
    restart: always
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '0:0'
    volumes:
      - ./grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
    networks:
      - promnet
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: '10.0.244.247:6379'
      REDIS_PASSWORD: 'team3'
    command:
      - '--debug'
    restart: always
    networks:
      - promnet

networks:
  promnet:
    driver: bridge
