global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # 자신의 프로메테우스에서 수집

  - job_name: "Application"
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'hyunwoo-worker:9100' ] # 스프링부트 서버 도메인:포트