global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # 자신의 프로메테우스에서 수집

  - job_name: "Application"
    metrics_path: "/metrics"
    scrape_interval: 3s
    static_configs:
      - targets: [ "hyunwoo-worker:9100" ] # 스프링부트 서버 도메인:포트
  
  - job_name: "Application-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: [ "hyunwoo-worker:8080" ] # 스프링부트 서버 도메인:포트